# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_OxfmkIKyv7y_8WSD_NNxDqhD1aumrz
"""

# !pip install nameparser
# !pip install nltk

from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
import nltk
from nameparser.parser import HumanName
# nltk.download('all')
def get_names(output_links):
    def get_human_names(text):
        tokens = nltk.tokenize.word_tokenize(text)
        pos = nltk.pos_tag(tokens)
        sentt = nltk.ne_chunk(pos, binary = False)
        person_list = []
        person = []
        name = ""
        for subtree in sentt.subtrees(filter=lambda t: t.label() == 'PERSON'):
            for leaf in subtree.leaves():
                person.append(leaf[0])
            if len(person) > 1: #avoid grabbing lone surnames
                for part in person:
                    name += part + ' '
                if name[:-1] not in person_list:
                    person_list.append(name[:-1])
                name = ''
            person = []

        return (person_list)

    def get_names_from_text(site):

    
    # To get all text data from site/url
    
        # hdr = {'User-Agent': 'Mozilla/5.0'}
        # req = Request(site,headers=hdr)
        # page = urlopen(req)
        # soup = BeautifulSoup(page)

        # for script in soup(["script", "style"]):
        #     script.decompose()

        # strips = list(soup.stripped_strings)
        # #print(" ".join(strips))
        # inp_text=" ".join(strips)

    
        # To get name from url only 
        # """
        inp_text=site.replace('-',' ')
        inp_text=inp_text.replace('/',' ')
        inp_text=inp_text.title()
        # """

        names_list=get_human_names(inp_text)
        return names_list



    keywords=['Instagram','Facebook','Github','Reddit','Pininterest','Linkedin']

        

    output_names=[]
    for link in output_links:
        print(get_names_from_text(link))
        output_names+=get_names_from_text(link)

    print(output_names)
    print(set(output_names))
    return output_names
